### ISSUE TITLE
XML Sitemap - Urgent

### ISSUE THREAD

**Issue by mbeharry** [ConsenSys/consensys-website#1]
[ConsenSys.net XML Sitemap - Updated - 2018 Nov 7.zip](https://github.com/ConsenSys/consensys-website/files/2590063/ConsenSys.net.XML.Sitemap.-.Updated.-.2018.Nov.7.zip)
please upload this XML sitemap to the root directory of the site so it resolves to: https://consensys.net/sitemap.xml

**Comment by dlesaca** [comment]
@mbeharry the issue has been resolved.
