### ISSUE TITLE
Nav Hover Overlay Descriptions

### ISSUE THREAD

**Issue by SKL333** [ConsenSys/consensys-website#11]
This was requested months ago - seeing it live on here: https://staging.consensys.net/

Just needs to be pushed live.

**Comment by dlesaca** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[CWEB-] Nav Hover Overlay Descriptions](https://trello.com/c/BM42mxK1/19-cweb-nav-hover-overlay-descriptions)

**Comment by kibagateaux** [comment]
This was [merged into production](https://github.com/ConsenSys/consensys-irving/pull/54) back in September. I verified that the code is in the codebase as well and it's also working on staging. 

[Relevant code](https://github.com/ConsenSys/consensys-irving/blob/c7bc4b7048be31c9f8c556fcd7c9c5ac191b580d/components/menu/index.js#L34-L37): 
```jsx
{hoverText && (
  <span className={`${styles.hoverText}`}>
    {hoverText}
  </span>
)}
```

My guess is that we haven't provided the `hoverText` in the Wordpress module interface on production yet.
