### ISSUE TITLE
https://consensys.net/ - Footer 

### ISSUE THREAD

**Issue by heymagruder** [ConsenSys/consensys-website#12]
Please update the spelling of ConsenSys in the copyright on the lower left of the footer.

**Comment by dlesaca** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[CWEB-] https://consensys.net/ - Footer](https://trello.com/c/CDO7Peap/18-cweb-https-consensysnet-footer)

**Comment by dlesaca** [comment]
@heymagruder "2019 © CONSENSUS SYSTEMS" is correct.
