### ISSUE TITLE
Update header logo to horizontal lock-up

### ISSUE THREAD

**Issue by SKL333** [ConsenSys/consensys-website#15]
SVG attached.

[consensys-logo-horizontal.svg.zip](https://github.com/ConsenSys/consensys-website/files/2857519/consensys-logo-horizontal.svg.zip)

**Comment by SKL333** [comment]
With menu icon update, header nav would look like:

![Uploading Screen Shot 2019-02-12 at 2.24.18 PM.png…]()

**Comment by dlesaca** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update header logo to horizontal lock-up](https://trello.com/c/pi8gc4HM/15-update-header-logo-to-horizontal-lock-up)

**Comment by kibagateaux** [comment]
@SKL333 what should the dimensions be for the horizontal lockup? First image is just replacing it in current container at 100px wide, the second is at 200px wide. Also should the alignment with the menu icon be, align top?

### 100px
<img width="1280" alt="Screen Shot 2019-04-18 at 7 14 09 PM" src="https://user-images.githubusercontent.com/22554244/56354041-c7576080-620d-11e9-9869-e0a13a26a1fc.png">

### 200px
<img width="1278" alt="Screen Shot 2019-04-18 at 7 18 43 PM" src="https://user-images.githubusercontent.com/22554244/56354206-23ba8000-620e-11e9-9eb5-de4aebd5667a.png">

**Comment by SKL333** [comment]
200px

We want to update that Menu icon also.

[menu-icon-new.svg.zip](https://github.com/ConsenSys/consensys-website/files/3095040/menu-icon-new.svg.zip)
