### ISSUE TITLE
Add GDPR Legal to site

### ISSUE THREAD

**Issue by heymagruder** [ConsenSys/consensys-website#19]

**Comment by dlesaca** [comment]
@heymagruder Please clarify.

**Comment by heymagruder** [comment]
I believe this was a legal requirement that needed to be on the site. Maybe Shawn Lee can provide some context.

**Comment by dlesaca** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[CWEB-19] Add GDPR Legal to site](https://trello.com/c/QEu64Ktp/10-cweb-19-add-gdpr-legal-to-site)

**Comment by dlesaca** [comment]
Reopening. After further investigation, the GDPR banner is not appearing as it should.

Requirement:
- GDPR banner should appear at top of page
