### ISSUE TITLE
feature request: uploading PDFs

### ISSUE THREAD

**Issue by zunaira-a** [ConsenSys/consensys-website#2]
Feature request: need ability to upload pdf through admin that will be hosted on site.
feature upgrade: ability to edit slug, title tag, and meta description for these pdfs

**Comment by SKL333** [comment]
@zunaira-a PR has been uploading PDFs of their press releases directly into the "Media Library"

Seeing the ability to edit all those other things (click into the document and click **Edit more details**.)

<img width="1226" alt="screen shot 2018-11-21 at 8 07 49 pm" src="https://user-images.githubusercontent.com/43786486/48875815-2fbe2500-edc9-11e8-8b2b-d07ffd377750.png">

**Comment by SKL333** [comment]
Closes #2
