### ISSUE TITLE
Kaleido Careers Page Links to Broken Redirect on Consensys Careers 

### ISSUE THREAD

**Issue by carolinacurbylucier** [ConsenSys/consensys-website#22]
The Kaleido career page links to open positions at this URL https://consensys.net/open-roles/?discipline=52454  but when I save it in Wordpress, it seems to redirect to https://consensys.net/open-roles/?discipline=52454&__hstc=49458809.b1585d36ce88ad9a745db360ed95d775.1550247556626.1554990724133.1554992839996.114&__hssc=49458809.2.1554992839996&__hsfp=1997848491    -- Our developer believes the issue is on your end and related to Hubspot URLs. Thanks

**Comment by dlesaca** [comment]
@carolinacurbylucier I'm not quite sure I understand the issue. Could you please clarify?

**Comment by carolinacurbylucier** [comment]
I think the issue has now been resolved. Thanks
