### ISSUE TITLE
Logos in Highlighted List Module

### ISSUE THREAD

**Issue by heymagruder** [ConsenSys/consensys-website#24]
Can we increase the size of the logos that are in these modules? I would say ~30% would be enough, but happy to provide a visual if needed.

<img width="1383" alt="screen_shot_2019-04-10_at_9 01 36_am" src="https://user-images.githubusercontent.com/5545077/56429146-1b4e5d80-627f-11e9-9b00-de66cbf67f55.png">

**Comment by kibagateaux** [comment]
Do you have a url where I can view this? I assume this isn't health.consensys.net since that's a different app.

**Comment by kibagateaux** [comment]
Increased sizing is live @heymagruder
