### ISSUE TITLE
Add scrollTo on hiring page

### ISSUE THREAD

**Issue by bdresser** [ConsenSys/consensys-website#3]
`https://consensys.net/open-roles/#metamask` should scroll me to the metamask section of the careers site. we have no way of sharing our roles directly with people.

This is super important for hiring funnels across the mesh - one of the company's biggest pain points! And is an easy fix.

**Comment by SKL333** [comment]
Agreed.

For now, this URL (not as pretty) could work until this gets resolved?

https://consensys.net/open-roles/?discipline=32543

**Comment by bdresser** [comment]
yep that works for me! not sure when that was updated, but it definitely solves my problem.

feel free to close this if you'd like

**Comment by SKL333** [comment]
Closes #3
