### ISSUE TITLE
Robots.txt file needed in the root directory

### ISSUE THREAD

**Issue by mbeharry** [ConsenSys/consensys-website#6]
We need a robots.txt file in the root with the file path to the xml sitemap.  ie: https://consensys.net/robots.txt

**Comment by dlesaca** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Robots.txt file needed in the root directory](https://trello.com/c/n6ljQ8gP/22-robotstxt-file-needed-in-the-root-directory)

**Comment by dlesaca** [comment]
resolved
